# Generated by Django 6.0 on 2026-01-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="插件名称"
                    ),
                ),
                (
                    "plugin_type",
                    models.CharField(
                        choices=[
                            ("data", "数据记录类"),
                            ("collect", "数据采集类"),
                            ("risk", "风险检测类"),
                            ("dump", "数据导出类"),
                            ("alarm", "告警类"),
                        ],
                        max_length=50,
                        verbose_name="插件类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="插件描述")),
                (
                    "file_path",
                    models.CharField(max_length=255, verbose_name="插件文件路径"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "插件",
                "verbose_name_plural": "插件",
                "db_table": "plugins",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("server", "服务器"),
                            ("account", "账户"),
                            ("port", "端口"),
                            ("process", "进程"),
                            ("middleware", "中间件"),
                            ("ai_component", "AI组件"),
                            ("database", "数据库"),
                            ("web_service", "Web服务"),
                            ("software", "软件"),
                            ("cron_task", "计划任务"),
                            ("startup_item", "启动项"),
                            ("kernel_module", "内核模块"),
                            ("web_site", "Web站点"),
                            ("idc_probe", "IDC探针发现"),
                        ],
                        max_length=50,
                        verbose_name="资产类型",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="资产UUID"
                    ),
                ),
                (
                    "host_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="主机UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="名称"),
                ),
                ("data", models.JSONField(default=dict, verbose_name="资产详细数据")),
                (
                    "source",
                    models.CharField(
                        default="aliyun_security",
                        max_length=50,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="采集时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "资产",
                "verbose_name_plural": "资产",
                "db_table": "assets",
                "indexes": [
                    models.Index(
                        fields=["asset_type", "host_uuid"],
                        name="assets_asset_t_cff74b_idx",
                    ),
                    models.Index(
                        fields=["collected_at"], name="assets_collect_caf9ee_idx"
                    ),
                ],
                "unique_together": {("asset_type", "uuid")},
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("paused", "已暂停"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动执行"),
                            ("cron", "定时执行"),
                            ("interval", "间隔执行"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="例如: 0 0 * * * (每天0点执行)",
                        max_length=100,
                        null=True,
                        verbose_name="Cron表达式",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="插件执行所需的配置参数",
                        verbose_name="任务配置",
                    ),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后执行时间"
                    ),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次执行时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=50, verbose_name="创建人"),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.plugin",
                        verbose_name="关联插件",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "db_table": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                ("result", models.JSONField(default=dict, verbose_name="执行结果")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                ("logs", models.TextField(blank=True, verbose_name="执行日志")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="app.task",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务执行记录",
                "verbose_name_plural": "任务执行记录",
                "db_table": "task_executions",
                "ordering": ["-started_at"],
            },
        ),
    ]
