# Generated by Django 6.0 on 2026-01-04 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AliyunConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="用于区分不同的配置",
                        max_length=100,
                        verbose_name="配置名称",
                    ),
                ),
                (
                    "api_endpoint",
                    models.CharField(
                        default="https://sas.cn-hangzhou.aliyuncs.com",
                        max_length=200,
                        verbose_name="API地址",
                    ),
                ),
                (
                    "access_key_id",
                    models.CharField(max_length=100, verbose_name="AccessKey ID"),
                ),
                (
                    "access_key_secret",
                    models.CharField(max_length=200, verbose_name="AccessKey Secret"),
                ),
                (
                    "region_id",
                    models.CharField(
                        default="cn-hangzhou", max_length=50, verbose_name="地域ID"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="每个用户只能有一个默认配置",
                        verbose_name="是否默认",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliyun_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "阿里云配置",
                "verbose_name_plural": "阿里云配置",
                "db_table": "aliyun_configs",
                "ordering": ["-is_default", "-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
