# Generated by Django 6.0 on 2026-01-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_aliyunconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="aliyun_config",
            field=models.ForeignKey(
                blank=True,
                help_text="选择使用的阿里云配置，为空则使用默认配置",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.aliyunconfig",
                verbose_name="阿里云配置",
            ),
        ),
    ]
