# Generated by Django 6.0 on 2026-01-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_vulnerability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aliyunconfig",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
            },
        ),
    ]
