# Generated by Django 6.0 on 2026-01-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_add_dingtalk_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliyunconfig",
            name="config_type",
            field=models.CharField(
                choices=[
                    ("aliyun", "阿里云配置"),
                    ("dingtalk", "钉钉配置"),
                    ("both", "阿里云+钉钉配置"),
                ],
                default="aliyun",
                max_length=20,
                verbose_name="配置类型",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="dingtalk_enabled",
            field=models.BooleanField(default=False, verbose_name="启用钉钉通知"),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="dingtalk_secret",
            field=models.CharField(
                blank=True,
                help_text="钉钉加签密钥（如使用加签方式）",
                max_length=200,
                verbose_name="钉钉签名密钥",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="dingtalk_webhook",
            field=models.URLField(
                blank=True,
                help_text="钉钉自定义机器人的Webhook地址",
                max_length=500,
                verbose_name="钉钉机器人Webhook",
            ),
        ),
        migrations.AlterField(
            model_name="aliyunconfig",
            name="access_key_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="AccessKey ID"
            ),
        ),
        migrations.AlterField(
            model_name="aliyunconfig",
            name="access_key_secret",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="AccessKey Secret"
            ),
        ),
        migrations.AlterField(
            model_name="aliyunconfig",
            name="api_endpoint",
            field=models.CharField(
                blank=True,
                default="https://sas.cn-hangzhou.aliyuncs.com",
                max_length=200,
                verbose_name="API地址",
            ),
        ),
        migrations.AlterField(
            model_name="aliyunconfig",
            name="region_id",
            field=models.CharField(
                blank=True, default="cn-hangzhou", max_length=50, verbose_name="地域ID"
            ),
        ),
    ]
