# Generated by Django 6.0 on 2026-01-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_aliyunconfig_config_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliyunconfig",
            name="qianwen_api_base",
            field=models.URLField(
                blank=True,
                default="https://dashscope.aliyuncs.com/compatible-mode/v1",
                help_text="API地址，中国大陆使用https://dashscope.aliyuncs.com/compatible-mode/v1",
                max_length=500,
                verbose_name="通义千问API地址",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="qianwen_api_key",
            field=models.CharField(
                blank=True,
                help_text="阿里云百炼平台的API Key",
                max_length=200,
                verbose_name="通义千问API Key",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="qianwen_enabled",
            field=models.BooleanField(
                default=False,
                help_text="是否启用AI模型解析漏洞详情",
                verbose_name="启用AI解析",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="qianwen_model",
            field=models.CharField(
                blank=True,
                default="qwen-plus",
                help_text="模型名称，如：qwen-plus, qwen-max, qwen-deepseek",
                max_length=100,
                verbose_name="通义千问模型名称",
            ),
        ),
    ]
