# Generated by Django 6.0 on 2026-01-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_add_qianwen_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliyunconfig",
            name="feishu_enabled",
            field=models.BooleanField(default=False, verbose_name="启用飞书通知"),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="feishu_secret",
            field=models.CharField(
                blank=True,
                help_text="飞书加签密钥（如使用加签方式）",
                max_length=200,
                verbose_name="飞书签名密钥",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="feishu_webhook",
            field=models.URLField(
                blank=True,
                help_text="飞书自定义机器人的Webhook地址",
                max_length=500,
                verbose_name="飞书机器人Webhook",
            ),
        ),
        migrations.AlterField(
            model_name="aliyunconfig",
            name="config_type",
            field=models.CharField(
                choices=[
                    ("aliyun", "阿里云配置"),
                    ("dingtalk", "钉钉配置"),
                    ("feishu", "飞书配置"),
                    ("qianwen", "通义千问AI配置"),
                    ("both", "阿里云+钉钉配置"),
                ],
                default="aliyun",
                max_length=20,
                verbose_name="配置类型",
            ),
        ),
    ]
