# Generated by Django 6.0 on 2026-01-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_add_feishu_long_connection_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliyunconfig",
            name="qianwen_config",
            field=models.ForeignKey(
                blank=True,
                help_text="选择已存在的通义千问AI配置，用于飞书智能体功能",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feishu_configs",
                to="app.aliyunconfig",
                verbose_name="关联的AI配置",
            ),
        ),
        migrations.AlterField(
            model_name="aliyunconfig",
            name="feishu_webhook",
            field=models.URLField(
                blank=True,
                help_text="飞书自定义机器人的Webhook地址（用于发送消息）",
                max_length=500,
                verbose_name="飞书机器人Webhook",
            ),
        ),
    ]
