# Generated by Django 6.0 on 2026-01-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_add_qianwen_config_to_feishu"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliyunconfig",
            name="dingtalk_app_id",
            field=models.CharField(
                blank=True,
                help_text="钉钉机器人应用的App ID（用于流式推送）",
                max_length=100,
                verbose_name="钉钉App ID",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="dingtalk_app_secret",
            field=models.CharField(
                blank=True,
                help_text="钉钉机器人应用的App Secret（用于流式推送）",
                max_length=200,
                verbose_name="钉钉App Secret",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="dingtalk_use_stream_push",
            field=models.BooleanField(
                default=False,
                help_text="使用流式推送方式接收事件，无需公网地址",
                verbose_name="使用流式推送",
            ),
        ),
    ]
