# Generated by Django 6.0 on 2026-01-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_add_dingtalk_stream_push"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliyunconfig",
            name="dingtalk_client_id",
            field=models.CharField(
                blank=True,
                help_text="钉钉机器人应用的Client ID（用于智能体交互）",
                max_length=100,
                verbose_name="钉钉Client ID",
            ),
        ),
        migrations.AddField(
            model_name="aliyunconfig",
            name="dingtalk_client_secret",
            field=models.CharField(
                blank=True,
                help_text="钉钉机器人应用的Client Secret（用于智能体交互）",
                max_length=200,
                verbose_name="钉钉Client Secret",
            ),
        ),
        migrations.AlterField(
            model_name="aliyunconfig",
            name="dingtalk_app_id",
            field=models.CharField(
                blank=True,
                help_text="钉钉机器人应用的App ID（用于智能体交互）",
                max_length=100,
                verbose_name="钉钉App ID",
            ),
        ),
        migrations.AlterField(
            model_name="aliyunconfig",
            name="dingtalk_app_secret",
            field=models.CharField(
                blank=True,
                help_text="钉钉机器人应用的App Secret（用于流式推送，已废弃，建议使用Client Secret）",
                max_length=200,
                verbose_name="钉钉App Secret",
            ),
        ),
    ]
