# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_security_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyunconfig',
            name='dingtalk_ai_card_template_id',
            field=models.CharField(max_length=100, blank=True, verbose_name='钉钉AI卡片模板ID', help_text='用于流式AI卡片回复的模板ID（在钉钉开发者后台创建）'),
        ),
        migrations.AddField(
            model_name='aliyunconfig',
            name='dingtalk_enable_stream_card',
            field=models.BooleanField(default=False, verbose_name='启用流式AI卡片', help_text='是否使用流式AI卡片进行回复（打字机效果）'),
        ),
    ]
