# Generated by Django 6.0 on 2026-01-21 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_add_security_alert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="用于区分不同的配置",
                        max_length=100,
                        verbose_name="配置名称",
                    ),
                ),
                (
                    "access_key_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Access Key ID"
                    ),
                ),
                (
                    "secret_access_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Secret Access Key"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="ap-northeast-1",
                        help_text="AWS区域，如：ap-northeast-1 (东京)",
                        max_length=50,
                        verbose_name="区域",
                    ),
                ),
                (
                    "session_token",
                    models.CharField(
                        blank=True,
                        help_text="临时凭证的Session Token（可选）",
                        max_length=500,
                        verbose_name="Session Token",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="每个用户只能有一个默认配置",
                        verbose_name="是否默认",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AWS配置",
                "verbose_name_plural": "AWS配置",
                "db_table": "aws_configs",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="securityalert",
            new_name="security_al_alert_t_5cd8ed_idx",
            old_name="security_al_alert_t_38b5d2_idx",
        ),
        migrations.RenameIndex(
            model_name="securityalert",
            new_name="security_al_level_8f9823_idx",
            old_name="security_al_level_d32b4a_idx",
        ),
        migrations.RenameIndex(
            model_name="securityalert",
            new_name="security_al_pushed__7c8240_idx",
            old_name="security_al_pushed__a7f8b2_idx",
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="asset",
            name="source",
            field=models.CharField(
                default="aliyun_security",
                help_text="数据来源：aliyun_security（阿里云安全中心）或 aws_inspector（AWS Inspector）",
                max_length=50,
                verbose_name="数据来源",
            ),
        ),
        migrations.AlterField(
            model_name="securityalert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("asset_type", "uuid", "source")},
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["source"], name="assets_source_28768d_idx"),
        ),
        migrations.AddField(
            model_name="awsconfig",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aws_configs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="aws_config",
            field=models.ForeignKey(
                blank=True,
                help_text="选择使用的AWS配置，为空则使用默认配置",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.awsconfig",
                verbose_name="AWS配置",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="awsconfig",
            unique_together={("user", "name")},
        ),
    ]
