# Generated by Django 6.0 on 2026-02-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_add_ai_card_template"),
        ("app", "0016_hexstrike_execution"),
    ]

    operations = []
