# Generated by Django 6.0 on 2026-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_merge_20260208_2146"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hexstrikeexecution",
            new_name="hexstrike_e_target_0940a2_idx",
            old_name="hexstrike_e_target_4a8b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="hexstrikeexecution",
            new_name="hexstrike_e_status_4652fc_idx",
            old_name="hexstrike_e_status_8c9d3e_idx",
        ),
        migrations.RenameIndex(
            model_name="vulnerability",
            new_name="vulnerabili_source_10dfd9_idx",
            old_name="vulnerabili_source_8a1f0d_idx",
        ),
        migrations.AlterField(
            model_name="hexstrikeexecution",
            name="execution_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="执行耗时（秒）"
            ),
        ),
    ]
