# Generated by Django 6.0 on 2026-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_chatsession_chatmessage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("server", "服务器"),
                    ("account", "账户"),
                    ("port", "端口"),
                    ("process", "进程"),
                    ("middleware", "中间件"),
                    ("ai_component", "AI组件"),
                    ("database", "数据库"),
                    ("web_service", "Web服务"),
                    ("software", "软件"),
                    ("cron_task", "计划任务"),
                    ("startup_item", "启动项"),
                    ("kernel_module", "内核模块"),
                    ("web_site", "Web站点"),
                    ("idc_probe", "IDC探针发现"),
                    ("vpc", "VPC实例"),
                    ("vswitch", "交换机"),
                    ("route_table", "路由表"),
                    ("nat_gateway", "NAT网关"),
                    ("ipv4_gateway", "IPv4网关"),
                    ("vpc_peer_connection", "VPC对等连接"),
                ],
                max_length=50,
                verbose_name="资产类型",
            ),
        ),
    ]
