# Generated by Django 6.0 on 2026-02-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_asset_asset_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_id",
                    models.CharField(
                        help_text="格式: {asset_type}_{timestamp}",
                        max_length=50,
                        unique=True,
                        verbose_name="快照ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(max_length=50, verbose_name="资产类型"),
                ),
                (
                    "source",
                    models.CharField(
                        default="aliyun_ecs", max_length=50, verbose_name="数据来源"
                    ),
                ),
                (
                    "asset_uuids",
                    models.JSONField(default=list, verbose_name="资产UUID列表"),
                ),
                (
                    "asset_count",
                    models.IntegerField(default=0, verbose_name="资产数量"),
                ),
                (
                    "asset_details",
                    models.JSONField(
                        default=dict,
                        help_text="UUID -> 资产简要信息的映射",
                        verbose_name="资产详情映射",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="与上次快照对比的变化",
                        verbose_name="变化记录",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="采集时间"),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=50, verbose_name="创建人"),
                ),
                (
                    "notification_sent",
                    models.BooleanField(default=False, verbose_name="已发送通知"),
                ),
                (
                    "notification_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="通知发送时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "资产快照",
                "verbose_name_plural": "资产快照",
                "db_table": "asset_snapshots",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["asset_type", "-collected_at"],
                        name="asset_snaps_asset_t_cebe17_idx",
                    ),
                    models.Index(
                        fields=["source", "-collected_at"],
                        name="asset_snaps_source_4e69a0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetChangeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "新增"),
                            ("deleted", "删除"),
                            ("modified", "变更"),
                        ],
                        max_length=20,
                        verbose_name="变更类型",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(max_length=50, verbose_name="资产类型"),
                ),
                (
                    "asset_uuid",
                    models.CharField(max_length=100, verbose_name="资产UUID"),
                ),
                (
                    "asset_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="资产名称"
                    ),
                ),
                ("old_value", models.JSONField(default=dict, verbose_name="变更前值")),
                ("new_value", models.JSONField(default=dict, verbose_name="变更后值")),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="检测时间"),
                ),
                ("notified", models.BooleanField(default=False, verbose_name="已通知")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_records",
                        to="app.assetsnapshot",
                        verbose_name="关联快照",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产变更记录",
                "verbose_name_plural": "资产变更记录",
                "db_table": "asset_change_records",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["change_type", "-detected_at"],
                        name="asset_chang_change__cc2dd7_idx",
                    ),
                    models.Index(
                        fields=["asset_type", "asset_uuid"],
                        name="asset_chang_asset_t_9cfbcb_idx",
                    ),
                ],
            },
        ),
    ]
